apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kyle-heller/Platform-Starter-Kit.git
    targetRevision: main
    path: infrastructure/kasten
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
