apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: updog-monitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kyle-heller/UpDog-Monitor.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: updog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
